version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: ./
    environment:
      DB_HOST: db
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
