version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: ./
    environment:
      DB_HOST: db
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db
      - minio1
      - minio2

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  minio1:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./uploads/s3/data1-1:/data1
      - ./uploads/s3/data1-2:/data2
    ports:
      - '9000:9000'
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./uploads/s3/data2-1:/data1
      - ./uploads/s3/data2-2:/data2
    ports:
      - '9001:9000'
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pg_data:
    driver: local
